  
---
title: "STAT 184" 
subtitle: "Street or Road"
author: "eric weah"
output: html_notebook
---





```{r}
# clean up workspace environment
rm(list = ls())
# all packages used for the assignment
library(mosaic)
library(tidyverse)
library(DataComputing)
library(tidyverse)
library(tidyr)
library(lubridate)
```

```{r}
download.file(url="http://tiny.cc/dcf/CMS_ProvidersSimple.rds",
              destfile = "YourNameForTheFile.rds")
DataTable <- readRDS("YourNameForTheFile.rds")
```

```{r}
Addresses <- read_csv("http://tiny.cc/dcf/street-addresses.csv")
Sample <- 
  Addresses %>%
  sample_n(size = 50)

```

```{r}
Matches <- 
  Sample %>%
  filter(grepl(pattern = "PO", address))

```

```{r}
Dont <- 
  Sample %>%
  filter( ! grepl(pattern = "PO", address))
```

```{r}
pattern <- "BOX\\s+(\\d+)"

Matches <- 
  Sample %>% 
  filter(grepl(pattern, address))

Dont <-
  Sample %>%
  filter( ! grepl(pattern, address))
Dont

BoxNumbers <- 
  Sample %>%
  filter(grepl(pattern, address)) %>%
  tidyr::extract(address, into = "boxnum", regex = pattern)

```
```{r}
Addresses <- read_csv("http://tiny.cc/dcf/street-addresses.csv")
Sample <- 
  Addresses %>%
  sample_n(size = 50)

```
Your turn: Read the following R statements. Next to each line, give a short explanation of what the line contributes to the task. For each of the regexes, explain in simple everyday language what pattern is being matched.

```{r}
pattern <- "( PO|POINT|COURT|PKWY|PLACE|PATH|ROAD|LN|CIRCLE|CT|LANDING|HEIGHTS)" ## creates a pattern for leftovers
LeftOvers <-  ##variable name for data table  
  Addresses %>% ## pulls from the data data
  filter( ! grepl(pattern, address), ##removes values from pattern 
          ! grepl("\\sAPT|UNIT\\s[\\d]+$", address), ## filter apt or unit that are found at the end
          ! grepl(" BOX ", address)## filter the box cases both begining and end
          )
```

```{r}
Matches <-
  Addresses %>%
  filter(!grepl(pattern = "PO", address),
         ! grepl("PO", address),
         ! grepl("POINT", address),
         ! grepl("COURT", address),
         ! grepl("PKWY", address),
         ! grepl("PLACE", address),
         ! grepl("PATH", address),
         ! grepl("ROAD", address),
         ! grepl("LN", address),
         ! grepl("CIRCLE", address),
         ! grepl("CT", address),
         ! grepl("LANDING", address),
         ! grepl("HEIGHTS", address)
         )
```

```{r}
DescOrder <- Matches %>% group_by(address) %>% summarise(total = n()) %>% arrange(desc(total))
DescOrder
```
```{r}
PopOfAdd <- PopMatches %>% filter(rank(desc(total)) <= 10)
PopOfAdd
```
### GGPLOT
```{r}
ggplot(data = TopAddresses, aes(x = reorder(address,-total), y = total)) + geom_bar(stat = 'identity', position = 'stack', width = 0.9)
```
